### ISSUE TITLE
Sensor.h missing

### ISSUE THREAD

**Issue by bean3511** [warehog/esphome-diesel-heater-ble#1]
Trying to compile the esphome firmware I get an error, unable to find platform diesel_heater_ble. Issue with the sensor component.
Heater.h includes sensor.h but the file is missing from the directory tree.

**Comment by warehog** [comment]
You must include at least one button, sensor, switch, number in yaml config, so that esphome configurator includes all necessary header files.
It's unresolved bug on my side, since I believe it's build in esphome feature to include required headers automatically, but I didn't managed to make it work.

```yaml
sensor:
  platform: diesel_heater_ble
  running_state:
    name: "Running State"
    id: running_state
  
number:
  - platform: diesel_heater_ble
    power_level:
      name: "Power Level"
      id: power_level

switch:
  - platform: diesel_heater_ble
    power:
      name: "Power"
      id: power_switch

button:
  - platform: diesel_heater_ble
    level_up:
      name: "Level Up"
      id: level_up_button
    level_down:
      name: "Level Down"
      id: level_down_button
```

Try with this minimal set of entities, and then adjust as needed.
